name: drizzle=bug
services:
  postgres:
    container_name: drizzle_bug
    image: postgres:17.0-alpine
    user: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: db
      POSTGRES_PASSWORD: admin
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
